/**
 * Precomputes the land dots for the hero globe from Natural Earth (world-atlas, 110m) so the
 * browser ships a small list of coordinates instead of a map library.
 *   node scripts/globe-data.mjs   → src/illustrations/landDots.ts
 */
import { geoContains } from 'd3-geo'
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { feature } from 'topojson-client'

const require = createRequire(import.meta.url)
const topo = JSON.parse(readFileSync(require.resolve('world-atlas/land-110m.json'), 'utf8'))
const land = feature(topo, topo.objects.land)

const STEP = 1.7 // degrees of latitude between rows
const dots = []
for (let lat = -58; lat <= 82; lat += STEP) {
  // Keep dots evenly spaced on the sphere: fewer per row towards the poles.
  const n = Math.round((360 / STEP) * Math.cos((lat * Math.PI) / 180))
  for (let i = 0; i < n; i++) {
    const lon = -180 + (i + (Math.round(lat / STEP) % 2 ? 0.5 : 0)) * (360 / n)
    if (geoContains(land, [lon, lat]))
      dots.push(Math.round(lon * 10) / 10, Math.round(lat * 10) / 10)
  }
}

// A coarse flat (equirectangular) map for small schematics: 4° cells, stored as [col,row] pairs.
const CELL = 4
const map = []
for (let row = 0; row * CELL < 140; row++) {
  const lat = 82 - row * CELL
  for (let col = 0; col * CELL < 360; col++) {
    const lon = -180 + col * CELL + CELL / 2
    if (geoContains(land, [lon, lat])) map.push(col, row)
  }
}
writeFileSync(
  'src/illustrations/worldMap.ts',
  `// Generated by scripts/globe-data.mjs from Natural Earth (public domain). Do not edit.\n` +
    `/** Land cells on a ${360 / CELL}×${140 / CELL} grid (4°, lat 82°N → 58°S): col,row,col,row,… */\n` +
    `export const MAP_COLS = ${360 / CELL}\nexport const MAP_ROWS = ${140 / CELL}\n` +
    `export const MAP_CELLS: readonly number[] = [${map.join(',')}]\n`,
)
console.log(`${map.length / 2} map cells`)

writeFileSync(
  'src/illustrations/landDots.ts',
  `// Generated by scripts/globe-data.mjs from Natural Earth (public domain). Do not edit.\n` +
    `/** Flat list of land sample points: lon, lat, lon, lat, … (degrees). */\n` +
    `export const LAND_DOTS: readonly number[] = [${dots.join(',')}]\n`,
)
console.log(`${dots.length / 2} land dots`)
